Product:
    type: entity
    table: product
    id:
        idProduct:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_product
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        price:
            type: float
            nullable: false
            options:
                fixed: false
        src:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 256
            options:
                fixed: false        
        primary_color:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        secondary_color:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        platform:
        ## add Platform entity => more sense/logical than putting it directly in the product entity
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        release_date:
            type: datetime
            nullable: true
            options:
                fixed: false
    lifecycleCallbacks: {  }
